database:
 # Database types currently available: MongoDB, MySQL
 type: 'MySQL'
 mysql:
  # Use Hikari
  hikari: false
  # Use MariaDB Driver
  mariadb: false
  # Host to access MySQL
  host: 'localhost'
  # Port to access MySQL
  port: '3306'
  # Database name in MySQL
  database: 'server'
  # MySQL access user
  user: 'root'
  # MySQL access password
  password: ''
 mongodb:
   # MongoDB Access URL
   # https://docs.mongodb.com/manual/reference/connection-string/
   url: ''
